C++: highlight return types when complaining about mismatches
This patch uses the BLT infrastructure to highlight the return type
of a function when complaining about code within the function that
doesn't match it.

For example, given:

  error: return-statement with a value, in function returning 'void' [-fpermissive]
     return 42;
            ^~

the patch adds this note:

  note: the return type was declared as 'void' here
   void test_1 (void)
   ^~~~

gcc/cp/ChangeLog:
	* cp-tree.h (attempt_to_highlight_return_type): New decl.
	* decl.c (finish_function): Call attempt_to_highlight_return_type
	when complaining about missing return statements in non-void
	functions.
	* typeck.c: Include "blt.h".
	(get_location_of_return_type): New function.
	(attempt_to_highlight_return_type): New function.
	(check_return_expr): Call attempt_to_highlight_return_type when
	complaining about return statements that mismatch the "void-ness"
	of the function.

gcc/testsuite/ChangeLog:
	* g++.dg/bad-return-type.C: New test case.