Add Dejagnu tests.
\ Add Dejagnu tests.

| Remove 64-bit ABI/arch tests

64-bit is not supported for nanoMIPS currently.

gcc/testsuite/
	* gcc.target/nanomips/dse-1.c: Delete.
	* gcc.target/nanomips/pr33256.c: Likewise.
	* gcc.target/nanomips/rsqrt-1.c: Likewise.
	* gcc.target/nanomips/rsqrt-2.c: Likewise.

| Skip target fpic tests for baremetal.

| Fix -rdynamic failure for g++.dg/lto/pr69589_0.C.

| Don't XFAIL 20040204-1.c for nanoMIPS.

This test passes for regular MIPS and also passes for nanoMIPS.

gcc/testsuite/

  * gcc.dg/tree-ssa/20040204-1.c (dg-final): Add nanomips*-*-* to the
  not-xfail target list.

| Skip loop-8.c for nanoMIPS.

This test was also skipped for regular MIPS.

gcc/testsuite/

  * gcc.dg/loop-8.c (dg-skip-if): Add nanomips*-*-* to the target list.

| Fix failure of const2.C.

This test is not adapted to the difference in output betweem LD and GOLD,
namely that gold prints an extra newline before we get to 'i':

gold:
/tmp/ccEbCXyD.o:const2.C:p':
(.sdata+0x0): error: undefined reference to 'A<int>::i'
collect2: error: ld returned 1 exit status

ld:
/tmp/cc4MSIIi.o:(.sdata+0x0): undefined reference to `A<int>::i'
collect2: error: ld returned 1 exit status

gcc/testsuite/

  * g++.old-deja/g++.pt/const2.C: Prune extra line printed by GOLD.

| GT-163: Fortify options of tests failing because of the large model.

| GT-165: Pass -mno-pid for failing .rodata tests.

gcc/testsuite/

  * g++.dg/cpp0x/constexpr-rom.C: Add dg-additional-options with -mno-pid for
  nanomips*-*-*.
  * gcc.dg/pr37303.c: Likewise.

| GT-247: Delete pr52125.c test

Test is no longer relevant as hi/lo relocs do not need to match and
we do not allow %lo in 'm' constraint for inline ASM.

gcc/testsuite/
	* gcc.target/nanomips/pr52125.c: Delete file.

| GT-259: Replace GP setup with LAPC and enable PIC (follow-up)

gcc/testsuite/gcc.target/nanomips/

  * nanomips-models-func-extern-auto-nmf.c: Check for LAPC instead of ALUIPC.
  * nanomips-models-func-extern-auto-nms.c: Likewise.
  * nanomips-models-func-extern-medium-nmf.c: Likewise.
  * nanomips-models-func-extern-medium-nms.c: Likewise.
  * nanomips-models-var-access-got-auto-nmf.c: Likewise.
  * nanomips-models-var-access-got-auto-nms.c: Likewise.
  * nanomips-models-var-access-got-medium-nmf.c: Likewise.
  * nanomips-models-var-access-got-medium-nms.c: Likewise.
  * nanomips-models-var-address-got-auto-nmf.c: Likewise.
  * nanomips-models-var-address-got-auto-nms.c: Likewise.
  * nanomips-models-var-address-got-medium-nmf.c: Likewise.
  * nanomips-models-var-address-got-medium-nms.c: Likewise.

| [testsuite] Require shared effective target for some lto.exp tests

Backport from trunk r244891

	* gcc.dg/lto/pr54709_0.c: Require 'shared' effective target.
	* gcc.dg/lto/pr61526_0.c: Likewise.
	* gcc.dg/lto/pr64415_0.c: Likewise.

| Fix long-term broken test for hoisting a modulo

This issue is long term broken and no longer discussed upstream. See
the bugzilla entry for pr38819 for detail.

gcc/testsuite/
	gcc.c-torture/execute/pr38819.c (dg-options): Disable checking
	for zero division for nanomips.

| Make c99_runtime unavailable for linux-musl. Add missing options for
some tests.

/ Require c99_runtime efffective target for builtin-convert-2.c.

| (split, tests) dmz #2763: code models: switch from suffixed instructions to pseudo-instructions

| (split, tests) GT-188: Implement GNU extension for nested functions

The GNU C extension allowing nested function definition for nanoMIPS.

gcc/testsuite/
    * lib/target-supports.exp (check_effective_target_trampolines) : Return 1
    for nanomips.
    * gcc.c-torture/execute/nestfunc-1.c: Remove xfail for nanomips.
    * gcc.c-torture/execute/nestfunc-2.c: Remove Likewise.
    * gcc.c-torture/execute/nestfunc-3.c: Remove Likewise.
    * gcc.c-torture/execute/nestfunc-5.c: Remove Likewise.
    * gcc.c-torture/execute/nestfunc-6.c: Remove Likewise.

| (split, tests) GT-234: Use %gprel instead of %gprel32 in the GP-relative addressing mode

gcc/testsuite/gcc.target/nanomips/
  * nanomips/nanomips-models-var-access-gprel-nmf.c (dg-final): Check for
  %gprel instead of %gprel32.
  * nanomips/nanomips-models-var-access-gprel-pid-nmf.c (dg-final): Likewise.
  * nanomips/nanomips-models-var-address-gprel-nmf.c (dg-final): Likewise.
  * nanomips/nanomips-models-var-address-gprel-pid-nmf.c (dg-final): Likewise.

| (split, tests) GT-259: Replace GP setup with LAPC and enable PIC

gcc/testsuite/
    * lib/target-supports.exp (check_effective_target_fpic): Remove
    nanomips-elf special case.

| (split, tests) GT-253: Fix failures in nested function support

Instructions needed to be written out in 16-bit chunks to avoid
unaligned 32-bit store issues.

gcc/testsuite/
    * gcc.c-torture/execute/20000822-1.c: Remove nanoMIPS special case.
    * gcc.c-torture/execute/921215-1.c: Likewise.
    * gcc.c-torture/execute/931002-1.c: Likewise.
    * gcc.dg/torture/stackalign/nested-5.c: Likewise.
    * gcc.dg/torture/stackalign/nested-6.c: Likewise.
    * gcc.dg/trampoline-1.c: Likewise.

| (split, tests) Remove fixme/user comments.

| (split, tests) GT-260: Use %got_call instead of %got_disp for medium model PIC calls.

gcc/testsuite/

  * gcc.target/nanomips/nanomips-models-func-extern-medium-nmf.c: Check for
  %got_call instead of %got_disp.
  * gcc.target/nanomips/nanomips-models-func-extern-medium-nms.c: Likewise.

| (split, dejagnu tests) GT-293[PATCH2]: Investigation into basic linkage for shared libraries

gcc/testsuite/

        * gcc.target/nanomips/beqic-1.c: Match variation of a local label.
        * gcc.target/nanomips/bgeiuc-1.c: Likewise.
        * gcc.target/nanomips/bltiuc-1.c: Likewise.

| Add constraint-m.c