Make def_chain public in the gori map instead of protected as I need it for this:
/source/gcc/gcc/tree-ssa-threadbackward.c: In member function ‘tree_node* bb_paths::terminal_name()’:
/source/gcc/gcc/tree-ssa-threadbackward.c:116:19: error: ‘ssa_define_chain gori::def_chain’ is protected within this context
     return ranger.def_chain.terminal_name (name);
                   ^~~~~~~~~